// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  events

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( BPFEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BPFEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BPFEventSerializer *BPFEventSerializer

func ( BPFFilterEventSerializer ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* BPFFilterEventSerializer ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_BPFFilterEventSerializer *BPFFilterEventSerializer
