## Log level, options are: panic, fatal, error, warn, info, debug or trace
log_level: debug

## JSON output file, leave empty to disable JSON output.
output: "/tmp/lolo.json"

## BTF information for the current kernel in .tar.xz format (required only if KRIE isn't able to locate it by itself)
vmlinux: ""

## events configuration
events:
  ## action taken when an init_module event is detected
  init_module: log

  ## action taken when an delete_module event is detected
  delete_module: nop

  ## action taken when a bpf event is detected
  bpf: nop

  ## action taken when a bpf_filter event is detected
  bpf_filter: nop

  ## action taken when a ptrace event is detected
  ptrace: nop

  ## action taken when a kprobe event is detected
  kprobe: nop

  ## action taken when a sysctl event is detected
  sysctl:
    action: nop

    ## Default settings for sysctl
    sysctl_default:
      block_read_access: false
      block_write_access: false

    ## Custom settings for sysctl
    sysctl_parameters:
      kernel/yama/ptrace_scope:
        block_write_access: true
      kernel/ftrace_enabled:
        override_input_value_with: "1\n"

  ## action taken when a hooked_syscall_table event is detected
  hooked_syscall_table: log

  ## action taken when a hooked_syscall event is detected
  hooked_syscall: log